Repository Autodesk/synthesis, pull requests merged in 2021-03, with the labels that each got.

#681 Fixed Numpy bug
  exporter/SynthesisFusionGltfExporter/SynthesisFusionGltfExporter.py
Labels: bug, fusion

#707 Update to WPILib 2020 Support
  emulation/hel/CMakeLists.txt
  emulation/hel/external_configs/grpc.patch
  emulation/hel/scripts/build_grpc.sh
  emulation/java_vm/Dockerfile
Labels: emulator

#706 Added Module Template
  modules/ModuleTemplate/Assets/metadata.xml
  modules/ModuleTemplate/Class1.cs
  modules/ModuleTemplate/ModuleTemplate.csproj
  modules/ModuleTemplate/SynthesisModule.vstemplate
  modules/ModuleTemplate/__TemplateIcon.png
  modules/README.md
  modules/modules.sln
Labels: module

#709 Update Emulator for WPILib 2021.2.2 Support
  emulation/hel/CMakeLists.txt
  emulation/hel/src/init.cpp
  emulation/hel/src/interrupt_manager.cpp
  emulation/java_vm/Dockerfile
  emulation/java_vm/wpi_cross/FRCDriverStation.patch
Labels: emulator
