Repository Autodesk/synthesis, pull requests merged in 2024-08, with the labels that each got.

#1066 Real Case Usage Exporter Fixes
  exporter/SynthesisFusionAddin/src/UI/ConfigCommand.py
Labels: bug, exporter

#1072 Bug: blue border on toggle button groups
  fission/src/ui/components/ToggleButtonGroup.tsx
Labels: bug, ui/ux

#1067 Internal Traffic Analytics Flag
  fission/src/systems/World.ts
  fission/src/systems/analytics/AnalyticsSystem.ts
Labels: analytics

#1075 Operation Remove the Javascript
  .gitattributes
Labels: documentation

#1074 Bug: Friction Override Slider Shown on Startup
  exporter/SynthesisFusionAddin/src/Parser/ExporterOptions.py
Labels: bug, exporter

#1076 Exporter Install `readme` + `codelab` [AARD-1742]
  README.md
  installer/Linux/.gitignore
  installer/Linux/README.md
  installer/Linux/Synthesis.AppDir/.DirIcon
  installer/Linux/Synthesis.AppDir/AppRun
  installer/Linux/Synthesis.AppDir/synthesis.desktop
  installer/Linux/Synthesis.AppDir/synthesis.png
  installer/Linux/package.sh
  installer/OSX-DMG/.gitignore
  installer/OSX-DMG/README.md
  installer/OSX-DMG/SynthesisMacInstallerBackground.png
  installer/OSX-DMG/exporter-install-instructions.md
  installer/OSX-DMG/license.txt
  installer/OSX-DMG/make-installer.sh
  installer/OSX/.gitignore
  installer/OSX/App/payload/Contents/Info.plist
  installer/OSX/App/payload/Contents/README.md
  installer/OSX/App/scripts/postinstall
  installer/OSX/App/scripts/preinstall
  installer/OSX/Assets/payload/Contents/Info.plist
  installer/OSX/Assets/payload/Contents/Synthesis/README.md
  installer/OSX/Assets/scripts/postinstall
  installer/OSX/Assets/scripts/preinstall
  installer/OSX/Exporter/payload/Contents/Info.plist
  installer/OSX/Exporter/payload/Contents/SynthesisInventorGltfExporter/README.md
  installer/OSX/Exporter/scripts/postinstall
  installer/OSX/Exporter/scripts/preinstall
  installer/OSX/Installer/Distribution.xml
  installer/OSX/Installer/Resources/conclusion.html
  installer/OSX/Installer/Resources/license.html
  installer/OSX/Installer/Resources/welcome.html
  installer/OSX/README.md
  installer/OSX/pkginstall
  installer/README.md
  installer/Windows/.gitignore
  installer/Windows/MainInstaller.nsi
  installer/Windows/README.md
  installer/Windows/W21_SYN_sidebar.bmp
  installer/Windows/orange-install-nsis.ico
  installer/Windows/orange-r.bmp
  installer/Windows/synthesis-logo-64x64.ico
  installer/exporter/.gitignore
  installer/exporter/README.md
  installer/exporter/create.sh
  installer/exporter/install.bat
  installer/exporter/install.sh
  installer/exporter/setup.bat
  tutorials/FusionExporter.md
  tutorials/img/fusion/fusion-add-addin.png
  tutorials/img/fusion/fusion-addin-synthesis.png
  tutorials/img/fusion/fusion-addins-highlight.png
  tutorials/img/fusion/fusion-addins-panel.png
  tutorials/img/fusion/fusion-empty.png
  tutorials/img/fusion/fusion-utilities-with-synthesis.png
Labels: documentation, exporter

#1024 AARD-1741: Exporter PIP Dependency Updates
  exporter/SynthesisFusionAddin/Synthesis.py
  exporter/SynthesisFusionAddin/proto/deps.py
  exporter/SynthesisFusionAddin/src/Dependencies.py
  exporter/SynthesisFusionAddin/src/general_imports.py
Labels: bug, exporter

#1082 Mirabuf Caching OPFS Back Up
  fission/src/mirabuf/MirabufLoader.ts
  fission/src/mirabuf/MirabufParser.ts
  fission/src/ui/panels/DebugPanel.tsx
Labels: bug

#1081 Exporter Formatting Fix
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Components.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/JointHierarchy.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Joints.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Materials.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Parser.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/PhysicalProperties.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/RigidGroup.py
  exporter/SynthesisFusionAddin/tools/verifyIsortFormatting.py
Labels: bug, exporter

#1087 `fission` Unit Test Fix
  .github/workflows/FissionUnitTest.yml
Labels: bug, testing

#1083 Fixed scrollbar
  fission/src/index.css
Labels: ui/ux

#1013 Convert to Absolute Imports `[AARD-1737]`
  exporter/SynthesisFusionAddin/Synthesis.py
  exporter/SynthesisFusionAddin/src/APS/APS.py
  exporter/SynthesisFusionAddin/src/Dependencies.py
  exporter/SynthesisFusionAddin/src/GlobalManager.py
  exporter/SynthesisFusionAddin/src/Logging.py
  exporter/SynthesisFusionAddin/src/Parser/ExporterOptions.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Components.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/JointHierarchy.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Joints.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Materials.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Parser.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/PhysicalProperties.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/RigidGroup.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Utilities.py
  exporter/SynthesisFusionAddin/src/UI/Camera.py
  exporter/SynthesisFusionAddin/src/UI/ConfigCommand.py
  exporter/SynthesisFusionAddin/src/UI/Configuration/SerialCommand.py
  exporter/SynthesisFusionAddin/src/UI/CreateCommandInputsHelper.py
  exporter/SynthesisFusionAddin/src/UI/CustomGraphics.py
  exporter/SynthesisFusionAddin/src/UI/Events.py
  exporter/SynthesisFusionAddin/src/UI/FileDialogConfig.py
  exporter/SynthesisFusionAddin/src/UI/GamepieceConfigTab.py
  exporter/SynthesisFusionAddin/src/UI/GeneralConfigTab.py
  exporter/SynthesisFusionAddin/src/UI/HUI.py
  exporter/SynthesisFusionAddin/src/UI/Handlers.py
  exporter/SynthesisFusionAddin/src/UI/Helper.py
  exporter/SynthesisFusionAddin/src/UI/IconPaths.py
  exporter/SynthesisFusionAddin/src/UI/JointConfigTab.py
  exporter/SynthesisFusionAddin/src/UI/MarkingMenu.py
  exporter/SynthesisFusionAddin/src/UI/ShowAPSAuthCommand.py
  exporter/SynthesisFusionAddin/src/UI/ShowWebsiteCommand.py
  exporter/SynthesisFusionAddin/src/UI/Toolbar.py
  exporter/SynthesisFusionAddin/src/__init__.py
  exporter/SynthesisFusionAddin/src/general_imports.py
  exporter/SynthesisFusionAddin/src/strings.py
Labels: exporter

#1068 Combined Configuration
  fission/index.html
  fission/src/Synthesis.tsx
  fission/src/systems/input/DefaultInputs.ts
  fission/src/systems/input/InputSystem.ts
  fission/src/systems/preferences/PreferenceTypes.ts
  fission/src/systems/simulation/Brain.ts
  fission/src/systems/simulation/behavior/synthesis/ArcadeDriveBehavior.ts
  fission/src/systems/simulation/behavior/synthesis/GenericArmBehavior.ts
  fission/src/systems/simulation/behavior/synthesis/GenericElevatorBehavior.ts
  fission/src/systems/simulation/behavior/synthesis/SequenceableBehavior.ts
  fission/src/systems/simulation/driver/HingeDriver.ts
  fission/src/systems/simulation/driver/SliderDriver.ts
  fission/src/systems/simulation/synthesis_brain/SynthesisBrain.ts
  fission/src/ui/components/Checkbox.tsx
  fission/src/ui/components/MainHUD.tsx
  fission/src/ui/components/SelectButton.tsx
  fission/src/ui/components/SelectMenu.tsx
  fission/src/ui/components/StyledComponents.tsx
  fission/src/ui/modals/configuring/ConfigureRobotModal.tsx
  fission/src/ui/modals/configuring/inputs/ChangeInputsModal.tsx
  fission/src/ui/modals/configuring/theme-editor/AssignNewSchemeModal.tsx
  fission/src/ui/modals/configuring/theme-editor/NewInputSchemeModal.tsx
  fission/src/ui/modals/spawning/ManageAssembliesModal.tsx
  fission/src/ui/panels/configuring/ChooseInputSchemePanel.tsx
  fission/src/ui/panels/configuring/ConfigureRobotBrainPanel.tsx
  fission/src/ui/panels/configuring/assembly-config/ConfigurePanel.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/ConfigureGamepiecePickupInterface.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/ConfigureShotTrajectoryInterface.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/SequentialBehaviorsInterface.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/inputs/ConfigureInputsInterface.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/inputs/ConfigureSchemeInterface.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/inputs/EditInputInterface.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/scoring/ConfigureScoringZonesInterface.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/scoring/ManageZonesInterface.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/scoring/ZoneConfigInterface.tsx
  fission/src/ui/panels/configuring/scoring/ScoringZonesPanel.tsx
  fission/src/ui/panels/mirabuf/ImportMirabufPanel.tsx
Labels: ui/ux

#1071 Moving Import Local Mirabuf
  fission/src/ui/components/MainHUD.tsx
  fission/src/ui/modals/mirabuf/ImportLocalMirabufModal.tsx
  fission/src/ui/panels/mirabuf/ImportMirabufPanel.tsx
Labels: gameplay

#1036 Cascading Shadows
  fission/src/mirabuf/MirabufInstance.ts
  fission/src/systems/scene/SceneRenderer.ts
  fission/src/ui/modals/configuring/SettingsModal.tsx
Labels: ui/ux

#1088 Track Compiled Proto Files
  exporter/SynthesisFusionAddin/README.md
  exporter/SynthesisFusionAddin/Synthesis.py
  exporter/SynthesisFusionAddin/pyproject.toml
  exporter/SynthesisFusionAddin/src/Dependencies.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Components.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/JointHierarchy.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Joints.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Materials.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Parser.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/PhysicalProperties.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/RigidGroup.py
  exporter/SynthesisFusionAddin/src/Proto/__init__.py
  exporter/SynthesisFusionAddin/src/Proto/assembly_pb2.py
  exporter/SynthesisFusionAddin/src/Proto/joint_pb2.py
  exporter/SynthesisFusionAddin/src/Proto/material_pb2.py
  exporter/SynthesisFusionAddin/src/Proto/motor_pb2.py
  exporter/SynthesisFusionAddin/src/Proto/readme.md
  exporter/SynthesisFusionAddin/src/Proto/signal_pb2.py
  exporter/SynthesisFusionAddin/src/Proto/types_pb2.py
Labels: documentation, exporter

#1050 CAN Support
  fission/src/systems/simulation/SimulationSystem.ts
  fission/src/systems/simulation/driver/WheelDriver.ts
  fission/src/systems/simulation/stimulus/ChassisStimulus.ts
  fission/src/systems/simulation/stimulus/EncoderStimulus.ts
  fission/src/systems/simulation/stimulus/HingeStimulus.ts
  fission/src/systems/simulation/stimulus/SliderStimulus.ts
  fission/src/systems/simulation/stimulus/Stimulus.ts
  fission/src/systems/simulation/stimulus/WheelStimulus.ts
  fission/src/systems/simulation/wpilib_brain/SimInput.ts
  fission/src/systems/simulation/wpilib_brain/SimOutput.ts
  fission/src/systems/simulation/wpilib_brain/WPILibBrain.ts
  fission/src/systems/simulation/wpilib_brain/WPILibWSWorker.ts
  fission/src/ui/components/Modal.tsx
  fission/src/ui/modals/configuring/rio-config/RCConfigCANGroupModal.tsx
  fission/src/ui/modals/configuring/rio-config/RCConfigEncoderModal.tsx
  fission/src/ui/modals/configuring/rio-config/RCConfigPWMGroupModal.tsx
  fission/src/ui/modals/configuring/rio-config/RCCreateDeviceModal.tsx
  fission/src/ui/panels/WSViewPanel.tsx
  fission/vite.config.ts
  simulation/.gitignore
  simulation/SyntheSimJava/.classpath
  simulation/SyntheSimJava/.gitignore
  simulation/SyntheSimJava/.project
  simulation/SyntheSimJava/.settings/org.eclipse.buildship.core.prefs
  simulation/SyntheSimJava/.settings/org.eclipse.jdt.core.prefs
  simulation/SyntheSimJava/src/main/java/com/autodesk/synthesis/CANEncoder.java
  simulation/SyntheSimJava/src/main/java/com/autodesk/synthesis/CANMotor.java
  simulation/SyntheSimJava/src/main/java/com/autodesk/synthesis/ctre/TalonFX.java
  simulation/SyntheSimJava/src/main/java/com/autodesk/synthesis/ctre/TalonFXConfigurator.java
  simulation/SyntheSimJava/src/main/java/com/autodesk/synthesis/revrobotics/CANSparkMax.java
  simulation/SyntheSimJava/src/main/java/com/autodesk/synthesis/revrobotics/SparkAbsoluteEncoder.java
  simulation/SyntheSimJava/vendordeps/Phoenix6.json
  simulation/SyntheSimJava/vendordeps/REVLib.json
  simulation/samples/CppSample/.project
  simulation/samples/CppSample/.settings/org.eclipse.buildship.core.prefs
  simulation/samples/JavaSample/.classpath
  simulation/samples/JavaSample/.gitignore
  simulation/samples/JavaSample/.project
  simulation/samples/JavaSample/.settings/org.eclipse.buildship.core.prefs
  simulation/samples/JavaSample/.settings/org.eclipse.jdt.core.prefs
  simulation/samples/JavaSample/src/main/java/frc/robot/Robot.java
  simulation/samples/JavaSample/vendordeps/Phoenix6.json
  simulation/samples/JavaSample/vendordeps/REVLib.json
Labels: codesim

#1077 More Simulation Support
  fission/src/systems/simulation/SimulationSystem.ts
  fission/src/systems/simulation/stimulus/ChassisStimulus.ts
  fission/src/systems/simulation/stimulus/EncoderStimulus.ts
  fission/src/systems/simulation/stimulus/HingeStimulus.ts
  fission/src/systems/simulation/stimulus/SliderStimulus.ts
  fission/src/systems/simulation/stimulus/Stimulus.ts
  fission/src/systems/simulation/stimulus/WheelStimulus.ts
  fission/src/systems/simulation/wpilib_brain/SimInput.ts
  fission/src/systems/simulation/wpilib_brain/SimOutput.ts
  fission/src/systems/simulation/wpilib_brain/WPILibBrain.ts
  fission/src/ui/modals/configuring/rio-config/RCConfigCANGroupModal.tsx
  fission/src/ui/modals/configuring/rio-config/RCConfigEncoderModal.tsx
  fission/src/ui/modals/configuring/rio-config/RCConfigPWMGroupModal.tsx
  fission/src/ui/modals/configuring/rio-config/RCCreateDeviceModal.tsx
  fission/src/ui/panels/WSViewPanel.tsx
  simulation/.gitignore
  simulation/samples/JavaSample/src/main/java/frc/robot/Robot.java
Labels: codesim

#1089 UI Continuity
  fission/index.html
  fission/src/Synthesis.tsx
  fission/src/main.tsx
  fission/src/mirabuf/IntakeSensorSceneObject.ts
  fission/src/systems/input/InputSystem.ts
  fission/src/ui/components/Button.tsx
  fission/src/ui/components/Checkbox.tsx
  fission/src/ui/components/Dropdown.tsx
  fission/src/ui/components/Label.tsx
  fission/src/ui/components/MainHUD.tsx
  fission/src/ui/components/Modal.tsx
  fission/src/ui/components/Panel.tsx
  fission/src/ui/components/SelectButton.tsx
  fission/src/ui/components/Slider.tsx
  fission/src/ui/components/StyledComponents.tsx
  fission/src/ui/components/ToggleButtonGroup.tsx
  fission/src/ui/modals/ViewModal.tsx
  fission/src/ui/modals/configuring/SettingsModal.tsx
  fission/src/ui/modals/mirabuf/ImportLocalMirabufModal.tsx
  fission/src/ui/modals/spawning/SpawningModals.tsx
  fission/src/ui/panels/DebugPanel.tsx
  fission/src/ui/panels/configuring/ChooseInputSchemePanel.tsx
  fission/src/ui/panels/configuring/assembly-config/ConfigurePanel.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/ConfigureGamepiecePickupInterface.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/SequentialBehaviorsInterface.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/inputs/ConfigureSchemeInterface.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/inputs/EditInputInterface.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/scoring/ConfigureScoringZonesInterface.tsx
  fission/src/ui/panels/mirabuf/ImportMirabufPanel.tsx
Labels: enhancement, ui/ux

#1092 File Save Permission Detection `[AARD-1724]`
  exporter/SynthesisFusionAddin/src/UI/ConfigCommand.py
  exporter/SynthesisFusionAddin/src/UI/FileDialogConfig.py
Labels: bug, exporter

#1073 Exporter Packaging and Installer `[AARD-1742]`
  .gitignore
  exporter/SynthesisFusionAddin/Synthesis.manifest
  exporter/SynthesisFusionAddin/src/Logging.py
  exporter/SynthesisFusionAddin/src/Types.py
  exporter/SynthesisFusionAddin/src/UI/Camera.py
  exporter/SynthesisFusionAddin/src/UI/ConfigCommand.py
  exporter/SynthesisFusionAddin/src/UI/Configuration/SerialCommand.py
  exporter/SynthesisFusionAddin/src/Util.py
  exporter/SynthesisFusionAddin/src/__init__.py
  installer/README.md
  installer/exporter/OSX/Scripts/preinstall
  installer/exporter/OSX/build.sh
  installer/exporter/OSX/distribution.xml
  installer/exporter/OSX/synthesis.bundle/Contents/Info.plist
  installer/exporter/README.md
  installer/exporter/Windows/build.bat
  installer/exporter/Windows/installer.py
  installer/exporter/Windows/requirements.txt
  installer/exporter/synthesis.bundle/PackageContents.xml
  tutorials/FusionExporter.md
Labels: packaging, exporter

#1090 Fission `README.md` and `package.json` updates
  fission/README.md
  fission/package.json
Labels: documentation

#1093 Exporter Typing with `mypy` `[AARD-1765]`
  .github/workflows/FusionTyping.yml
  exporter/SynthesisFusionAddin/Synthesis.py
  exporter/SynthesisFusionAddin/mypy.ini
  exporter/SynthesisFusionAddin/proto/build.bat
  exporter/SynthesisFusionAddin/proto/build.sh
  exporter/SynthesisFusionAddin/requirements-dev.txt
  exporter/SynthesisFusionAddin/requirements-mypy.txt
  exporter/SynthesisFusionAddin/src/APS/APS.py
  exporter/SynthesisFusionAddin/src/Dependencies.py
  exporter/SynthesisFusionAddin/src/GlobalManager.py
  exporter/SynthesisFusionAddin/src/Logging.py
  exporter/SynthesisFusionAddin/src/Parser/ExporterOptions.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Components.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/JointHierarchy.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Joints.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Materials.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/PDMessage.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Parser.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/PhysicalProperties.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/RigidGroup.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Utilities.py
  exporter/SynthesisFusionAddin/src/Proto/assembly_pb2.pyi
  exporter/SynthesisFusionAddin/src/Proto/joint_pb2.pyi
  exporter/SynthesisFusionAddin/src/Proto/material_pb2.pyi
  exporter/SynthesisFusionAddin/src/Proto/motor_pb2.pyi
  exporter/SynthesisFusionAddin/src/Proto/signal_pb2.pyi
  exporter/SynthesisFusionAddin/src/Proto/types_pb2.pyi
  exporter/SynthesisFusionAddin/src/Types.py
  exporter/SynthesisFusionAddin/src/UI/Camera.py
  exporter/SynthesisFusionAddin/src/UI/ConfigCommand.py
  exporter/SynthesisFusionAddin/src/UI/Configuration/SerialCommand.py
  exporter/SynthesisFusionAddin/src/UI/CustomGraphics.py
  exporter/SynthesisFusionAddin/src/UI/Events.py
  exporter/SynthesisFusionAddin/src/UI/FileDialogConfig.py
  exporter/SynthesisFusionAddin/src/UI/GamepieceConfigTab.py
  exporter/SynthesisFusionAddin/src/UI/GeneralConfigTab.py
  exporter/SynthesisFusionAddin/src/UI/HUI.py
  exporter/SynthesisFusionAddin/src/UI/Handlers.py
  exporter/SynthesisFusionAddin/src/UI/Helper.py
  exporter/SynthesisFusionAddin/src/UI/JointConfigTab.py
  exporter/SynthesisFusionAddin/src/UI/MarkingMenu.py
  exporter/SynthesisFusionAddin/src/UI/OsHelper.py
  exporter/SynthesisFusionAddin/src/UI/ShowAPSAuthCommand.py
  exporter/SynthesisFusionAddin/src/UI/ShowWebsiteCommand.py
  exporter/SynthesisFusionAddin/src/UI/Toolbar.py
  exporter/SynthesisFusionAddin/src/Util.py
  exporter/SynthesisFusionAddin/src/__init__.py
Labels: exporter, refactor

#1095 Unit Tests & Documentation
  fission/package.json
  fission/src/Synthesis.tsx
  fission/src/systems/input/DefaultInputs.ts
  fission/src/systems/input/InputSchemeManager.ts
  fission/src/systems/input/InputSystem.ts
  fission/src/systems/preferences/PreferenceTypes.ts
  fission/src/systems/preferences/PreferencesSystem.ts
  fission/src/systems/simulation/synthesis_brain/SynthesisBrain.ts
  fission/src/test/InputSystem.test.ts
  fission/src/test/PreferencesSystem.test.ts
  fission/src/test/ui/Button.test.tsx
  fission/src/test/ui/SelectMenu.test.tsx
  fission/src/ui/components/Button.tsx
  fission/src/ui/components/Checkbox.tsx
  fission/src/ui/components/Dropdown.tsx
  fission/src/ui/components/SelectMenu.tsx
  fission/src/ui/components/StyledComponents.tsx
  fission/src/ui/modals/configuring/inputs/ResetAllInputsModal.tsx
  fission/src/ui/panels/configuring/ChooseInputSchemePanel.tsx
Labels: documentation, testing

#1100 Settings modal scaling hotfix
  fission/src/ui/modals/configuring/SettingsModal.tsx
Labels: hotfix, ui/ux

#1099 Catch When No Design is Selected
  exporter/SynthesisFusionAddin/src/UI/ConfigCommand.py
Labels: exporter

#1097 Move subsystem config to the combined configuration panel
  fission/src/Synthesis.tsx
  fission/src/ui/components/MainHUD.tsx
  fission/src/ui/components/SelectMenu.tsx
  fission/src/ui/components/StyledComponents.tsx
  fission/src/ui/modals/configuring/SettingsModal.tsx
  fission/src/ui/panels/configuring/ConfigureSubsystemsPanel.tsx
  fission/src/ui/panels/configuring/assembly-config/ConfigurePanel.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/ConfigureSubsystemsInterface.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/SequentialBehaviorsInterface.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/SubsystemRowInterface.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/inputs/ConfigureInputsInterface.tsx
Labels: refactor

#1098 Importing Cached From Map Hotfix
  fission/src/Synthesis.tsx
  fission/src/mirabuf/MirabufLoader.ts
  fission/src/ui/panels/configuring/ConfigureRobotBrainPanel.tsx
  fission/src/ui/panels/mirabuf/ImportMirabufPanel.tsx
Labels: bug, hotfix

#1101 Utilize Fusion's Unit Manager `[AARD-1773]`
  exporter/SynthesisFusionAddin/src/Parser/ExporterOptions.py
  exporter/SynthesisFusionAddin/src/Resources/kg_icon/16x16-normal.png
  exporter/SynthesisFusionAddin/src/Resources/lbs_icon/16x16-normal.png
  exporter/SynthesisFusionAddin/src/Types.py
  exporter/SynthesisFusionAddin/src/UI/ConfigCommand.py
  exporter/SynthesisFusionAddin/src/UI/GamepieceConfigTab.py
  exporter/SynthesisFusionAddin/src/UI/GeneralConfigTab.py
  exporter/SynthesisFusionAddin/src/UI/IconPaths.py
  exporter/SynthesisFusionAddin/src/Util.py
Labels: exporter

#1094 SyntheSimJava Documentation
  simulation/SyntheSimJava/README.md
  simulation/SyntheSimJava/src/main/java/com/autodesk/synthesis/CANEncoder.java
  simulation/SyntheSimJava/src/main/java/com/autodesk/synthesis/CANMotor.java
  simulation/SyntheSimJava/src/main/java/com/autodesk/synthesis/ctre/TalonFX.java
  simulation/SyntheSimJava/src/main/java/com/autodesk/synthesis/ctre/TalonFXConfigurator.java
  simulation/SyntheSimJava/src/main/java/com/autodesk/synthesis/revrobotics/CANSparkMax.java
  simulation/SyntheSimJava/src/main/java/com/autodesk/synthesis/revrobotics/SparkAbsoluteEncoder.java
Labels: documentation, codesim

#1106 Final UI Tweaks
  fission/src/ui/components/Modal.tsx
  fission/src/ui/components/StyledComponents.tsx
  fission/src/ui/modals/configuring/SettingsModal.tsx
  fission/src/ui/modals/configuring/theme-editor/NewInputSchemeModal.tsx
  fission/src/ui/panels/configuring/ChooseInputSchemePanel.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/inputs/ConfigureInputsInterface.tsx
Labels: ui/ux

#1102 Open Synthesis Upon Export `[AARD-1772]`
  exporter/SynthesisFusionAddin/src/Parser/ExporterOptions.py
  exporter/SynthesisFusionAddin/src/UI/ConfigCommand.py
  exporter/SynthesisFusionAddin/src/UI/GeneralConfigTab.py
  exporter/SynthesisFusionAddin/src/__init__.py
Labels: exporter
