Repository Autodesk/synthesis, pull requests merged in 2024-07, with the labels that each got.

#991 Skybox
  fission/package-lock.json
  fission/package.json
  fission/src/Synthesis.tsx
  fission/src/Window.d.ts
  fission/src/shaders/fragment.glsl
  fission/src/shaders/vertex.glsl
  fission/src/systems/scene/SceneRenderer.ts
  fission/src/ui/components/Skybox.tsx
  fission/tsconfig.json
  fission/vite.config.ts
Labels: rendering

#1002 Additional `CODEOWNERS` subteams
  .github/CODEOWNERS
Labels: automation

#992 Mirabuf Caching
  .github/workflows/FissionESLintFormat.yml
  fission/bun.lockb
  fission/package-lock.json
  fission/package.json
  fission/prettier.config.js
  fission/src/Synthesis.tsx
  fission/src/mirabuf/MirabufInstance.ts
  fission/src/mirabuf/MirabufLoader.ts
  fission/src/mirabuf/MirabufParser.ts
  fission/src/mirabuf/MirabufSceneObject.ts
  fission/src/samples/JoltExample.tsx
  fission/src/systems/physics/PhysicsSystem.ts
  fission/src/test/MirabufParser.test.ts
  fission/src/test/PhysicsSystem.test.ts
  fission/src/ui/components/MainHUD.tsx
  fission/src/ui/modals/mirabuf/ImportLocalMirabufModal.tsx
  fission/src/ui/modals/spawning/SpawningModals.tsx
  fission/tsconfig.json
Labels: mirabuf

#986 Advanced Inputs
  fission/src/Synthesis.tsx
  fission/src/mirabuf/MirabufSceneObject.ts
  fission/src/systems/input/DefaultInputs.ts
  fission/src/systems/input/InputSystem.ts
  fission/src/systems/physics/Mechanism.ts
  fission/src/systems/physics/PhysicsSystem.ts
  fission/src/systems/simulation/behavior/ArcadeDriveBehavior.ts
  fission/src/systems/simulation/behavior/GenericArmBehavior.ts
  fission/src/systems/simulation/behavior/GenericElevatorBehavior.ts
  fission/src/systems/simulation/synthesis_brain/SynthesisBrain.ts
  fission/src/ui/components/Checkbox.tsx
  fission/src/ui/components/Dropdown.tsx
  fission/src/ui/modals/configuring/ChangeInputsModal.tsx
  fission/src/ui/modals/configuring/ResetAllInputsModal.tsx
  fission/vite.config.ts
Labels: gameplay

#998 Addable Transform Gizmos
  fission/src/systems/scene/SceneRenderer.ts
  fission/src/ui/components/MainHUD.tsx
  fission/src/ui/components/Scene.tsx
  fission/src/ui/components/TransformGizmo.tsx
Labels: ui/ux, gameplay

#1015 Random syntax error?
  fission/src/mirabuf/MirabufSceneObject.ts
Labels: hotfix

#1001 Exporter APS Authentication
  exporter/SynthesisFusionAddin/.gitignore
  exporter/SynthesisFusionAddin/Synthesis.py
  exporter/SynthesisFusionAddin/src/APS/APS.py
  exporter/SynthesisFusionAddin/src/Resources/APS/16x16-disabled.png
  exporter/SynthesisFusionAddin/src/Resources/APS/16x16-normal.png
  exporter/SynthesisFusionAddin/src/Resources/APS/32x32-disabled.png
  exporter/SynthesisFusionAddin/src/Resources/APS/32x32-normal.png
  exporter/SynthesisFusionAddin/src/Resources/APS/64x64-normal.png
  exporter/SynthesisFusionAddin/src/UI/ConfigCommand.py
  exporter/SynthesisFusionAddin/src/UI/ShowAPSAuthCommand.py
Labels: authentication

#1020 Quick Fix in dev
  fission/src/Synthesis.tsx
  fission/src/mirabuf/MirabufSceneObject.ts
  fission/src/systems/scene/SceneRenderer.ts
  fission/src/ui/components/Dropdown.tsx
  fission/src/ui/components/MainHUD.tsx
  fission/src/ui/components/TransformGizmo.tsx
Labels: hotfix

#1018 Codeowner Subteams Quick Fix
  .github/CODEOWNERS
Labels: hotfix, automation

#1011 General project cleanups
  .clang-format
  .gitattributes
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/not-sure-if-it-s-a-bug.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .gitignore
  .gitmodules
  README.md
Labels: documentation

#1009 Transform Gizmos on Mirabuf Assemblies
  .github/workflows/FissionUnitTest.yml
  fission/.gitignore
  fission/package-lock.json
  fission/src/mirabuf/MirabufSceneObject.ts
  fission/src/systems/physics/PhysicsSystem.ts
  fission/src/systems/scene/SceneRenderer.ts
  fission/src/ui/components/MainHUD.tsx
  fission/src/ui/components/TransformGizmo.tsx
  fission/src/ui/components/TransformGizmos.tsx
Labels: physics, ui/ux, gameplay

#1012 The Poker
  fission/src/Synthesis.tsx
  fission/src/mirabuf/MirabufInstance.ts
  fission/src/systems/physics/PhysicsSystem.ts
  fission/src/systems/scene/SceneRenderer.ts
  fission/src/ui/components/MainHUD.tsx
  fission/src/ui/components/Skybox.tsx
  fission/src/ui/components/Slider.tsx
  fission/src/ui/panels/PokerPanel.tsx
  fission/src/ui/panels/RobotSwitchPanel.tsx
  fission/src/util/TypeConversions.ts
Labels: testing

#1025 Quick Fix
  fission/src/Synthesis.tsx
  fission/src/ui/components/MainHUD.tsx
Labels: hotfix

#1022 Visual Touchups
  fission/.gitignore
  fission/package.json
  fission/src/Synthesis.tsx
  fission/src/mirabuf/MirabufSceneObject.ts
  fission/src/systems/scene/SceneRenderer.ts
Labels: rendering

#1008 Upgrade Import Modal
  fission/.env
  fission/bun.lockb
  fission/src/Synthesis.tsx
  fission/src/aps/APS.ts
  fission/src/aps/APSDataManagement.ts
  fission/src/mirabuf/MirabufLoader.ts
  fission/src/ui/ThemeContext.tsx
  fission/src/ui/ToastContext.tsx
  fission/src/ui/components/Button.tsx
  fission/src/ui/components/MainHUD.tsx
  fission/src/ui/components/Modal.tsx
  fission/src/ui/components/Panel.tsx
  fission/src/ui/components/ToggleButtonGroup.tsx
  fission/src/ui/modals/mirabuf/ImportMirabufModal.tsx
  fission/src/ui/panels/mirabuf/ImportMirabufPanel.tsx
  fission/src/util/TaskStatus.ts
  fission/src/vite-env.d.ts
  fission/vite.config.ts
Labels: ui/ux, aps

#1017 Intake and Ejector Configurator
  fission/src/Synthesis.tsx
  fission/src/mirabuf/EjectableSceneObject.ts
  fission/src/mirabuf/IntakeSensorSceneObject.ts
  fission/src/mirabuf/MirabufParser.ts
  fission/src/mirabuf/MirabufSceneObject.ts
  fission/src/systems/physics/Mechanism.ts
  fission/src/systems/physics/PhysicsSystem.ts
  fission/src/systems/preferences/PreferenceTypes.ts
  fission/src/systems/scene/SceneRenderer.ts
  fission/src/test/MirabufParser.test.ts
  fission/src/test/util/TypeConversions.test.ts
  fission/src/ui/components/MainHUD.tsx
  fission/src/ui/components/SelectButton.tsx
  fission/src/ui/components/Skybox.tsx
  fission/src/ui/components/Slider.tsx
  fission/src/ui/components/TransformGizmos.tsx
  fission/src/ui/modals/configuring/ConfigMotorModal.tsx
  fission/src/ui/modals/configuring/ConfigureRobotModal.tsx
  fission/src/ui/modals/configuring/SettingsModal.tsx
  fission/src/ui/panels/PokerPanel.tsx
  fission/src/ui/panels/configuring/ConfigureGamepiecePickupPanel.tsx
  fission/src/ui/panels/configuring/ConfigureShotTrajectoryPanel.tsx
  fission/src/ui/panels/configuring/scoring/ZoneConfigPanel.tsx
  fission/src/util/TypeConversions.ts
Labels: physics

#1023 Batched Rendering
  fission/src/mirabuf/MirabufInstance.ts
  fission/src/mirabuf/MirabufSceneObject.ts
  fission/src/ui/components/TransformGizmos.tsx
Labels: rendering

#1029 Build Errors
  .github/workflows/FissionBuild.yml
  fission/src/Synthesis.tsx
  fission/src/systems/preferences/PreferencesSystem.ts
  fission/src/ui/modals/configuring/ResetAllInputsModal.tsx
  fission/src/ui/panels/configuring/scoring/ZoneConfigPanel.tsx
Labels: bug, automation

#1021 Scoring Zones Configuration
  fission/src/Synthesis.tsx
  fission/src/mirabuf/MirabufSceneObject.ts
  fission/src/systems/preferences/PreferenceTypes.ts
  fission/src/systems/preferences/PreferencesSystem.ts
  fission/src/systems/simulation/synthesis_brain/SynthesisBrain.ts
  fission/src/ui/PanelContext.tsx
  fission/src/ui/components/Checkbox.tsx
  fission/src/ui/components/MainHUD.tsx
  fission/src/ui/components/SelectButton.tsx
  fission/src/ui/components/TransformGizmos.tsx
  fission/src/ui/modals/configuring/ChangeInputsModal.tsx
  fission/src/ui/panels/configuring/scoring/ScoringZonesPanel.tsx
  fission/src/ui/panels/configuring/scoring/ZoneConfigPanel.tsx
Labels: gameplay

#1004 APS File Upload
  exporter/SynthesisFusionAddin/README.md
  exporter/SynthesisFusionAddin/Synthesis.py
  exporter/SynthesisFusionAddin/proto/deps.py
  exporter/SynthesisFusionAddin/src/APS/APS.py
  exporter/SynthesisFusionAddin/src/Parser/ExporterOptions.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Parser.py
  exporter/SynthesisFusionAddin/src/UI/ConfigCommand.py
  exporter/SynthesisFusionAddin/src/UI/ShowAPSAuthCommand.py
  exporter/SynthesisFusionAddin/src/general_imports.py
Labels: exporter, aps

#1031 Initial Code Simulation Support: WebSocket Client
  fission/src/Synthesis.tsx
  fission/src/systems/simulation/wpilib_brain/WPILibBrain.ts
  fission/src/systems/simulation/wpilib_brain/WPILibWSWorker.ts
  fission/src/ui/components/MainHUD.tsx
  fission/src/ui/panels/WSViewPanel.tsx
  fission/src/util/Lazy.ts
  simulation/README.md
  simulation/SyntheSimJava/.gitattributes
  simulation/SyntheSimJava/.gitignore
  simulation/SyntheSimJava/README.md
  simulation/SyntheSimJava/build.gradle
  simulation/SyntheSimJava/gradle.properties
  simulation/SyntheSimJava/gradle/libs.versions.toml
  simulation/SyntheSimJava/gradle/wrapper/gradle-wrapper.jar
  simulation/SyntheSimJava/gradle/wrapper/gradle-wrapper.properties
  simulation/SyntheSimJava/gradlew
  simulation/SyntheSimJava/gradlew.bat
  simulation/SyntheSimJava/settings.gradle
  simulation/SyntheSimJava/src/main/java/com/autodesk/synthesis/CANEncoder.java
  simulation/SyntheSimJava/src/main/java/com/autodesk/synthesis/CANMotor.java
  simulation/SyntheSimJava/src/main/java/com/autodesk/synthesis/ctre/TalonFX.java
  simulation/SyntheSimJava/src/main/java/com/autodesk/synthesis/revrobotics/CANSparkMax.java
  simulation/samples/CppSample/.gitignore
  simulation/samples/CppSample/WPILib-License.md
  simulation/samples/CppSample/build.gradle
  simulation/samples/CppSample/gradle/wrapper/gradle-wrapper.jar
  simulation/samples/CppSample/gradle/wrapper/gradle-wrapper.properties
  simulation/samples/CppSample/gradlew
  simulation/samples/CppSample/gradlew.bat
  simulation/samples/CppSample/settings.gradle
  simulation/samples/CppSample/src/main/cpp/Robot.cpp
  simulation/samples/CppSample/src/main/deploy/example.txt
  simulation/samples/CppSample/src/main/include/Robot.h
  simulation/samples/CppSample/src/test/cpp/main.cpp
  simulation/samples/CppSample/vendordeps/NavX.json
  simulation/samples/CppSample/vendordeps/Phoenix6.json
  simulation/samples/CppSample/vendordeps/REVLib.json
  simulation/samples/CppSample/vendordeps/WPILibNewCommands.json
  simulation/samples/JavaSample/.gitignore
  simulation/samples/JavaSample/WPILib-License.md
  simulation/samples/JavaSample/build.gradle
  simulation/samples/JavaSample/gradle/wrapper/gradle-wrapper.jar
  simulation/samples/JavaSample/gradle/wrapper/gradle-wrapper.properties
  simulation/samples/JavaSample/gradlew
  simulation/samples/JavaSample/gradlew.bat
  simulation/samples/JavaSample/settings.gradle
  simulation/samples/JavaSample/src/main/deploy/example.txt
  simulation/samples/JavaSample/src/main/java/frc/robot/Main.java
  simulation/samples/JavaSample/src/main/java/frc/robot/Robot.java
Labels: codesim

#1026 Loading Notification
  fission/src/Synthesis.tsx
  fission/src/mirabuf/MirabufInstance.ts
  fission/src/mirabuf/MirabufParser.ts
  fission/src/mirabuf/MirabufSceneObject.ts
  fission/src/test/PhysicsSystem.test.ts
  fission/src/ui/components/ProgressNotification.tsx
  fission/src/ui/components/ProgressNotificationData.ts
  fission/src/ui/panels/mirabuf/ImportMirabufPanel.tsx
  fission/src/util/EasingFunctions.ts
  fission/vite.config.ts
Labels: ui/ux

#1030 Scene Tags
  fission/src/Synthesis.tsx
  fission/src/mirabuf/MirabufSceneObject.ts
  fission/src/systems/preferences/PreferenceTypes.ts
  fission/src/systems/scene/SceneRenderer.ts
  fission/src/ui/components/SceneOverlay.tsx
  fission/src/ui/components/SceneOverlayEvents.ts
  fission/src/ui/modals/configuring/SettingsModal.tsx
Labels: ui/ux

#995 AARD-1685: Joint Config Panel
  exporter/SynthesisFusionAddin/src/Parser/ExporterOptions.py
  exporter/SynthesisFusionAddin/src/UI/ConfigCommand.py
  exporter/SynthesisFusionAddin/src/UI/CreateCommandInputsHelper.py
  exporter/SynthesisFusionAddin/src/UI/FileDialogConfig.py
  exporter/SynthesisFusionAddin/src/UI/JointConfigTab.py
Labels: exporter

#1039 `requests` dependency missing
  exporter/SynthesisFusionAddin/proto/deps.py
Labels: exporter

#1010 AARD-1735: Logging module updates
  exporter/SynthesisFusionAddin/Synthesis.py
  exporter/SynthesisFusionAddin/proto/deps.py
  exporter/SynthesisFusionAddin/src/Analytics/alert.py
  exporter/SynthesisFusionAddin/src/Analytics/poster.py
  exporter/SynthesisFusionAddin/src/Analyzer/sniff.py
  exporter/SynthesisFusionAddin/src/Analyzer/timer.py
  exporter/SynthesisFusionAddin/src/GlobalManager.py
  exporter/SynthesisFusionAddin/src/Logging.py
  exporter/SynthesisFusionAddin/src/Parser/ExporterOptions.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Components.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/JointHierarchy.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Joints.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Materials.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Parser.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/PhysicalProperties.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/RigidGroup.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Utilities.py
  exporter/SynthesisFusionAddin/src/UI/Camera.py
  exporter/SynthesisFusionAddin/src/UI/ConfigCommand.py
  exporter/SynthesisFusionAddin/src/UI/CreateCommandInputsHelper.py
  exporter/SynthesisFusionAddin/src/UI/CustomGraphics.py
  exporter/SynthesisFusionAddin/src/UI/Events.py
  exporter/SynthesisFusionAddin/src/UI/HUI.py
  exporter/SynthesisFusionAddin/src/UI/Helper.py
  exporter/SynthesisFusionAddin/src/UI/JointConfigTab.py
  exporter/SynthesisFusionAddin/src/UI/MarkingMenu.py
  exporter/SynthesisFusionAddin/src/UI/ShowAPSAuthCommand.py
  exporter/SynthesisFusionAddin/src/UI/Toolbar.py
  exporter/SynthesisFusionAddin/src/configure.py
  exporter/SynthesisFusionAddin/src/general_imports.py
  exporter/SynthesisFusionAddin/src/logging.py
  exporter/SynthesisFusionAddin/src/strings.py
Labels: exporter

#1034 Named robot controls
  fission/src/Synthesis.tsx
  fission/src/mirabuf/MirabufSceneObject.ts
  fission/src/systems/input/DefaultInputs.ts
  fission/src/systems/input/InputSchemeManager.ts
  fission/src/systems/input/InputSystem.ts
  fission/src/systems/preferences/PreferenceTypes.ts
  fission/src/systems/preferences/PreferencesSystem.ts
  fission/src/systems/simulation/behavior/ArcadeDriveBehavior.ts
  fission/src/systems/simulation/behavior/GenericArmBehavior.ts
  fission/src/systems/simulation/behavior/GenericElevatorBehavior.ts
  fission/src/systems/simulation/synthesis_brain/SynthesisBrain.ts
  fission/src/ui/components/MainHUD.tsx
  fission/src/ui/components/SceneOverlay.tsx
  fission/src/ui/components/SceneOverlayEvents.ts
  fission/src/ui/modals/configuring/ChangeInputsModal.tsx
  fission/src/ui/modals/configuring/ResetAllInputsModal.tsx
  fission/src/ui/modals/configuring/theme-editor/AssignNewSchemeModal.tsx
  fission/src/ui/modals/configuring/theme-editor/NewInputSchemeModal.tsx
  fission/src/ui/panels/configuring/ChooseInputSchemePanel.tsx
  fission/src/ui/panels/mirabuf/ImportMirabufPanel.tsx
Labels: gameplay

#1045 Refactor: `Types/**/*` -> `Types.py`
  exporter/SynthesisFusionAddin/Synthesis.py
  exporter/SynthesisFusionAddin/src/FLAGS.py
  exporter/SynthesisFusionAddin/src/Parser/ExporterOptions.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Components.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Joints.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Materials.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Parser.py
  exporter/SynthesisFusionAddin/src/Types.py
  exporter/SynthesisFusionAddin/src/UI/Camera.py
  exporter/SynthesisFusionAddin/src/UI/ConfigCommand.py
  exporter/SynthesisFusionAddin/src/UI/Configuration/SerialCommand.py
  exporter/SynthesisFusionAddin/src/UI/FileDialogConfig.py
  exporter/SynthesisFusionAddin/src/UI/JointConfigTab.py
  exporter/SynthesisFusionAddin/src/configure.py
Labels: exporter, refactor

#1038 UI Touchups
  fission/src/Synthesis.tsx
  fission/src/ui/components/MainHUD.tsx
  fission/src/ui/components/Toast.tsx
  fission/src/ui/components/Tooltip.tsx
  fission/src/ui/modals/ExitSynthesisModal.tsx
  fission/src/ui/modals/MatchResultsModal.tsx
  fission/src/ui/modals/UpdateAvailableModal.tsx
  fission/src/ui/modals/configuring/ResetAllInputsModal.tsx
  fission/src/ui/modals/configuring/theme-editor/DeleteAllThemesModal.tsx
  fission/src/ui/modals/configuring/theme-editor/DeleteThemeModal.tsx
  fission/src/ui/modals/mirabuf/ImportLocalMirabufModal.tsx
  fission/src/ui/modals/spawning/ManageAssembliesModal.tsx
  fission/src/ui/panels/DebugPanel.tsx
  fission/src/ui/panels/configuring/scoring/ScoringZonesPanel.tsx
  fission/src/ui/panels/configuring/scoring/ZoneConfigPanel.tsx
  fission/src/ui/panels/mirabuf/ImportMirabufPanel.tsx
Labels: ui/ux

#1046 Refactor: Remove `configure.py`
  exporter/SynthesisFusionAddin/Synthesis.py
  exporter/SynthesisFusionAddin/src/configure.py
Labels: exporter, refactor

#1042 Refactor: `ExporterOptions.py`
  exporter/SynthesisFusionAddin/src/Parser/ExporterOptions.py
  exporter/SynthesisFusionAddin/src/Types.py
Labels: exporter, refactor

#1048 APS Upload Pipeline Polish
  exporter/SynthesisFusionAddin/src/APS/APS.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Parser.py
  exporter/SynthesisFusionAddin/src/UI/ConfigCommand.py
Labels: exporter, aps

#1014 Friction Data Export
  exporter/SynthesisFusionAddin/src/Parser/ExporterOptions.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Materials.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Parser.py
  exporter/SynthesisFusionAddin/src/Resources/FrictionOverride_icon/32x32-normal.png
  exporter/SynthesisFusionAddin/src/UI/ConfigCommand.py
  fission/src/mirabuf/MirabufParser.ts
Labels: exporter

#1041 Removed scoring zone panels from the modals array
  fission/src/Synthesis.tsx
Labels: hotfix

#1016 APS Logout
  fission/src/aps/APS.ts
Labels: authentication

#1049 Analytics
  fission/index.html
  fission/package.json
  fission/src/GA.d.ts
  fission/src/Synthesis.tsx
  fission/src/aps/APS.ts
  fission/src/aps/APSDataManagement.ts
  fission/src/index.css
  fission/src/mirabuf/MirabufLoader.ts
  fission/src/systems/World.ts
  fission/src/systems/analytics/AnalyticsSystem.ts
  fission/src/ui/components/AnalyticsConsent.tsx
Labels: analytics

#1062 No scheme with APS bots bug
  fission/src/ui/panels/mirabuf/ImportMirabufPanel.tsx
Labels: bug

#1063 [HOTFIX 1] 7.0.0b1
  fission/src/Synthesis.tsx
  fission/src/systems/analytics/AnalyticsSystem.ts
  fission/src/systems/input/InputSchemeManager.ts
  fission/src/ui/components/Button.tsx
  fission/src/ui/components/MainHUD.tsx
  fission/src/ui/components/Modal.tsx
  fission/src/ui/modals/spawning/ManageAssembliesModal.tsx
  fission/src/ui/panels/configuring/ChooseInputSchemePanel.tsx
  fission/src/ui/panels/information/ScoreboardPanel.tsx
  fission/src/ui/panels/mirabuf/ImportMirabufPanel.tsx
Labels: no-merge

#1061 PWM Support
  fission/src/systems/simulation/wpilib_brain/WPILibBrain.ts
  fission/src/ui/panels/DebugPanel.tsx
Labels: codesim

#1032 Core Meta Panel & Gamepiece Configuration
  exporter/SynthesisFusionAddin/src/Parser/ExporterOptions.py
  exporter/SynthesisFusionAddin/src/UI/ConfigCommand.py
  exporter/SynthesisFusionAddin/src/UI/GamepieceConfigTab.py
  exporter/SynthesisFusionAddin/src/UI/GeneralConfigTab.py
  exporter/SynthesisFusionAddin/src/UI/JointConfigTab.py
  exporter/SynthesisFusionAddin/src/UI/TableUtilities.py
Labels: exporter

#1065 APS Required Login Fix
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Parser.py
Labels: bug, exporter, aps

#1053 Toolbar Buttons
  exporter/SynthesisFusionAddin/Synthesis.py
  exporter/SynthesisFusionAddin/src/Resources/SynthesisWebsite/16x16-disabled.png
  exporter/SynthesisFusionAddin/src/Resources/SynthesisWebsite/16x16-normal.png
  exporter/SynthesisFusionAddin/src/Resources/SynthesisWebsite/32x32-disabled.png
  exporter/SynthesisFusionAddin/src/Resources/SynthesisWebsite/32x32-normal.png
  exporter/SynthesisFusionAddin/src/Resources/SynthesisWebsite/64x64-normal.png
  exporter/SynthesisFusionAddin/src/UI/ShowWebsiteCommand.py
Labels: exporter

#1051 UI Touchups v2
  fission/src/Synthesis.tsx
  fission/src/systems/preferences/PreferenceTypes.ts
  fission/src/ui/components/Checkbox.tsx
  fission/src/ui/components/Dropdown.tsx
  fission/src/ui/components/Input.tsx
  fission/src/ui/components/MainHUD.tsx
  fission/src/ui/components/StyledComponents.tsx
  fission/src/ui/components/UserIcon.tsx
  fission/src/ui/modals/DownloadAssetsModal.tsx
  fission/src/ui/modals/ExitSynthesisModal.tsx
  fission/src/ui/modals/MatchResultsModal.tsx
  fission/src/ui/modals/UpdateAvailableModal.tsx
  fission/src/ui/modals/ViewModal.tsx
  fission/src/ui/modals/aether/ConnectToMultiplayerModal.tsx
  fission/src/ui/modals/aether/ServerHostingModal.tsx
  fission/src/ui/modals/configuring/ChooseMultiplayerModeModal.tsx
  fission/src/ui/modals/configuring/ChooseSingleplayerModeModal.tsx
  fission/src/ui/modals/configuring/ConfigMotorModal.tsx
  fission/src/ui/modals/configuring/ConfigureRobotModal.tsx
  fission/src/ui/modals/configuring/DrivetrainModal.tsx
  fission/src/ui/modals/configuring/PracticeSettingsModal.tsx
  fission/src/ui/modals/configuring/RoboRIOModal.tsx
  fission/src/ui/modals/configuring/SettingsModal.tsx
  fission/src/ui/modals/configuring/inputs/ChangeInputsModal.tsx
  fission/src/ui/modals/configuring/inputs/ResetAllInputsModal.tsx
  fission/src/ui/modals/configuring/rio-config/RCConfigCANGroupModal.tsx
  fission/src/ui/modals/configuring/rio-config/RCConfigEncoderModal.tsx
  fission/src/ui/modals/configuring/rio-config/RCConfigPWMGroupModal.tsx
  fission/src/ui/modals/configuring/rio-config/RCCreateDeviceModal.tsx
  fission/src/ui/modals/configuring/theme-editor/AssignNewSchemeModal.tsx
  fission/src/ui/modals/configuring/theme-editor/DeleteAllThemesModal.tsx
  fission/src/ui/modals/configuring/theme-editor/DeleteThemeModal.tsx
  fission/src/ui/modals/configuring/theme-editor/NewInputSchemeModal.tsx
  fission/src/ui/modals/configuring/theme-editor/NewThemeModal.tsx
  fission/src/ui/modals/configuring/theme-editor/ThemeEditorModal.tsx
  fission/src/ui/modals/mirabuf/ImportLocalMirabufModal.tsx
  fission/src/ui/modals/spawning/ManageAssembliesModal.tsx
  fission/src/ui/modals/spawning/MatchModeModal.tsx
  fission/src/ui/modals/spawning/SpawningModals.tsx
  fission/src/ui/panels/DebugPanel.tsx
  fission/src/ui/panels/PokerPanel.tsx
  fission/src/ui/panels/RobotSwitchPanel.tsx
  fission/src/ui/panels/WSViewPanel.tsx
  fission/src/ui/panels/configuring/ChooseInputSchemePanel.tsx
  fission/src/ui/panels/configuring/ConfigureGamepiecePickupPanel.tsx
  fission/src/ui/panels/configuring/ConfigureShotTrajectoryPanel.tsx
  fission/src/ui/panels/configuring/scoring/ScoringZonesPanel.tsx
  fission/src/ui/panels/configuring/scoring/ZoneConfigPanel.tsx
  fission/src/ui/panels/mirabuf/ImportMirabufPanel.tsx
  fission/src/ui/panels/simulation/DriverStationPanel.tsx
Labels: ui/ux
