Repository Autodesk/synthesis, pull requests merged in 2024-06, with the labels that each got.

#978 Small bug
  exporter/SynthesisFusionAddin/src/Parser/ParseOptions.py
  exporter/SynthesisFusionAddin/src/UI/ConfigCommand.py
Labels: bug

#977 Input Manager
  engine/Assets/Scripts/Drivers/WheelDriver.cs
  engine/Assets/Scripts/Utilities/ColorManager/ColorManager.cs
  fission/src/aps/APS.ts
  fission/src/mirabuf/MirabufSceneObject.ts
  fission/src/systems/World.ts
  fission/src/systems/input/InputSystem.ts
  fission/src/systems/simulation/SimulationSystem.ts
  fission/src/systems/simulation/behavior/ArcadeDriveBehavior.ts
  fission/src/systems/simulation/behavior/Behavior.ts
  fission/src/systems/simulation/behavior/GenericArmBehavior.ts
  fission/src/systems/simulation/behavior/GenericElevatorBehavior.ts
  fission/src/systems/simulation/driver/SliderDriver.ts
  fission/src/systems/simulation/driver/WheelDriver.ts
  fission/src/systems/simulation/stimulus/WheelStimulus.ts
  fission/src/systems/simulation/synthesis_brain/SynthesisBrain.ts
  fission/src/ui/modals/configuring/ChangeInputsModal.tsx
Labels: gameplay

#981 AARD-1687: Save exporter options with active design
  exporter/SynthesisFusionAddin/proto/deps.py
  exporter/SynthesisFusionAddin/src/Parser/ExporterOptions.py
  exporter/SynthesisFusionAddin/src/Parser/ParseOptions.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Components.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/JointHierarchy.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Joints.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Materials.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Parser.py
  exporter/SynthesisFusionAddin/src/UI/ConfigCommand.py
  exporter/SynthesisFusionAddin/src/UI/FileDialogConfig.py
  exporter/SynthesisFusionAddin/src/UI/Helper.py
Labels: exporter

#994 Physics & Suspension
  fission/src/systems/physics/PhysicsSystem.ts
  fission/src/systems/simulation/driver/WheelDriver.ts
Labels: physics

#984 `Fusion 360` -> `Fusion`
  exporter/README.md
  exporter/SynthesisFusionAddin/README.md
  exporter/SynthesisFusionAddin/Synthesis.py
  exporter/SynthesisFusionAddin/src/Parser/ExporterOptions.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Joints.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Materials.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/RigidGroup.py
  exporter/SynthesisFusionAddin/src/UI/Configuration/SerialCommand.py
  exporter/SynthesisFusionAddin/src/UI/HUI.py
  exporter/SynthesisFusionAddin/src/strings.py
Labels: documentation

#993 Windows assetpack download script
  fission/package.json
  fission/prettier.config.js
  fission/src/Synthesis.tsx
  fission/src/mirabuf/MirabufParser.ts
  fission/src/ui/ToastContext.tsx
  fission/src/ui/components/Dropdown.tsx
  fission/src/ui/components/NumberInput.tsx
  fission/src/ui/components/Scene.tsx
  fission/src/ui/modals/configuring/theme-editor/ThemeEditorModal.tsx
Labels: packaging

#990 God Mode: Physics
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/JointHierarchy.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Joints.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/PDMessage.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Parser.py
  exporter/SynthesisFusionAddin/src/UI/ConfigCommand.py
  exporter/SynthesisFusionAddin/src/UI/CustomGraphics.py
  exporter/SynthesisFusionAddin/src/UI/HUI.py
  exporter/SynthesisFusionAddin/src/UI/IconPaths.py
  exporter/SynthesisFusionAddin/src/UI/Toolbar.py
  fission/.gitignore
  fission/README.md
  fission/bun.lockb
  fission/src/mirabuf/MirabufSceneObject.ts
  fission/src/systems/World.ts
  fission/src/systems/input/InputSystem.ts
  fission/src/systems/physics/PhysicsSystem.ts
  fission/src/systems/simulation/SimulationSystem.ts
  fission/src/systems/simulation/behavior/ArcadeDriveBehavior.ts
  fission/src/systems/simulation/behavior/Behavior.ts
  fission/src/systems/simulation/behavior/GenericArmBehavior.ts
  fission/src/systems/simulation/behavior/GenericElevatorBehavior.ts
  fission/src/systems/simulation/driver/SliderDriver.ts
  fission/src/systems/simulation/driver/WheelDriver.ts
  fission/src/systems/simulation/stimulus/WheelStimulus.ts
  fission/src/systems/simulation/synthesis_brain/SynthesisBrain.ts
  fission/src/test/PhysicsSystem.test.ts
  fission/src/ui/components/MainHUD.tsx
  fission/src/ui/modals/configuring/ChangeInputsModal.tsx
Labels: gameplay

#980 AARD-1671: Fission import panel modal
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Parser.py
  exporter/SynthesisFusionAddin/src/UI/ConfigCommand.py
  exporter/SynthesisFusionAddin/src/general_imports.py
  fission/src/Synthesis.tsx
  fission/src/ui/components/MainHUD.tsx
  fission/src/ui/modals/mirabuf/ImportLocalMirabufModal.tsx
Labels: exporter

#983 Haverty/elevator bug
  fission/src/systems/input/InputSystem.ts
  fission/src/systems/simulation/behavior/GenericArmBehavior.ts
  fission/src/systems/simulation/behavior/GenericElevatorBehavior.ts
  fission/src/systems/simulation/driver/Driver.ts
  fission/src/systems/simulation/driver/HingeDriver.ts
  fission/src/systems/simulation/driver/SliderDriver.ts
Labels: bug, gameplay

#985 AARD-1710: Exporter auto formatter updates
  .github/workflows/BlackFormat.yml
  exporter/SynthesisFusionAddin/README.md
  exporter/SynthesisFusionAddin/Synthesis.py
  exporter/SynthesisFusionAddin/proto/deps.py
  exporter/SynthesisFusionAddin/pyproject.toml
  exporter/SynthesisFusionAddin/requirements.txt
  exporter/SynthesisFusionAddin/src/Analytics/alert.py
  exporter/SynthesisFusionAddin/src/Analytics/poster.py
  exporter/SynthesisFusionAddin/src/Analyzer/sniff.py
  exporter/SynthesisFusionAddin/src/Analyzer/timer.py
  exporter/SynthesisFusionAddin/src/GlobalManager.py
  exporter/SynthesisFusionAddin/src/Parser/ExporterOptions.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Components.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/JointHierarchy.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Joints.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Materials.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/PDMessage.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Parser.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/PhysicalProperties.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/RigidGroup.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Utilities.py
  exporter/SynthesisFusionAddin/src/Types/OString.py
  exporter/SynthesisFusionAddin/src/UI/Camera.py
  exporter/SynthesisFusionAddin/src/UI/ConfigCommand.py
  exporter/SynthesisFusionAddin/src/UI/Configuration/SerialCommand.py
  exporter/SynthesisFusionAddin/src/UI/CustomGraphics.py
  exporter/SynthesisFusionAddin/src/UI/Events.py
  exporter/SynthesisFusionAddin/src/UI/FileDialogConfig.py
  exporter/SynthesisFusionAddin/src/UI/HUI.py
  exporter/SynthesisFusionAddin/src/UI/Helper.py
  exporter/SynthesisFusionAddin/src/UI/IconPaths.py
  exporter/SynthesisFusionAddin/src/UI/MarkingMenu.py
  exporter/SynthesisFusionAddin/src/UI/OsHelper.py
  exporter/SynthesisFusionAddin/src/UI/Toolbar.py
  exporter/SynthesisFusionAddin/src/configure.py
  exporter/SynthesisFusionAddin/src/general_imports.py
  exporter/SynthesisFusionAddin/src/logging.py
  exporter/SynthesisFusionAddin/tools/format.py
  exporter/SynthesisFusionAddin/tools/verifyIsortFormatting.py
Labels: exporter, formatting

#997 Format Bun Fallback
  fission/package.json
Labels: formatting

#996 Vitest Playwright
  .github/workflows/FissionUnitTest.yml
  fission/README.md
  fission/package-lock.json
  fission/package.json
  fission/src/aps/APS.ts
  fission/src/mirabuf/MirabufLoader.ts
  fission/src/test/MirabufParser.test.ts
  fission/src/test/PhysicsSystem.test.ts
  fission/vite.config.ts
Labels: enhancement, physics, testing

#1000 refactored assetpack script
  fission/package.json
  fission/src/Synthesis.tsx
  fission/src/systems/input/InputSystem.ts
  fission/src/systems/simulation/behavior/GenericArmBehavior.ts
  fission/src/systems/simulation/behavior/GenericElevatorBehavior.ts
  fission/src/systems/simulation/driver/Driver.ts
  fission/src/systems/simulation/driver/HingeDriver.ts
  fission/src/systems/simulation/driver/SliderDriver.ts
  fission/src/ui/components/MainHUD.tsx
  fission/src/ui/modals/mirabuf/ImportLocalMirabufModal.tsx
Labels: refactor

#1005 Add Caching Assets to Workflow
  .github/workflows/FissionUnitTest.yml
  fission/bun.lockb
  fission/package-lock.json
  fission/package.json
Labels: testing, refactor

#989 Adaptive Physics Time Step
  .github/workflows/FissionESLintFormat.yml
  fission/package.json
  fission/src/mirabuf/MirabufParser.ts
  fission/src/systems/physics/PhysicsSystem.ts
  fission/src/systems/simulation/driver/HingeDriver.ts
  fission/src/systems/simulation/driver/SliderDriver.ts
  fission/src/ui/modals/mirabuf/ImportMirabufModal.tsx
  fission/src/ui/modals/spawning/SpawningModals.tsx
  fission/src/util/dom.ts
Labels: physics
