Repository Autodesk/synthesis, pull requests merged in 2024-03, with the labels that each got.

#958 MacOS Exporter Dependency Bug
  exporter/SynthesisFusionAddin/proto/deps.py
Labels: bug

#961 Auto request reviews update
  .github/CODEOWNERS
Labels: documentation

#968 World System and Basic Physics
  .github/workflows/FissionESLintFormat.yml
  .github/workflows/FissionPackage.yml
  .github/workflows/FissionUnitTest.yml
  fission/package.json
  fission/src/App.css
  fission/src/App.tsx
  fission/src/Synthesis.tsx
  fission/src/components/Scene.tsx
  fission/src/main.tsx
  fission/src/mirabuf/MirabufInstance.ts
  fission/src/mirabuf/MirabufParser.ts
  fission/src/mirabuf/MirabufSceneObject.ts
  fission/src/modals/spawning/AddRobotModal.tsx
  fission/src/modals/spawning/ManageAssembliesModal.tsx
  fission/src/panels/information/ScoreboardPanel.tsx
  fission/src/samples/JoltExample.tsx
  fission/src/samples/ThreeExample.tsx
  fission/src/systems/World.ts
  fission/src/systems/WorldSystem.ts
  fission/src/systems/physics/PhysicsSystem.ts
  fission/src/systems/scene/SceneRenderer.ts
  fission/src/systems/world/WorldSystem.ts
  fission/src/test/MirabufParser.test.ts
  fission/src/test/PhysicsSystem.test.ts
  fission/src/test/World.test.ts
  fission/src/util/TypeConversions.ts
  fission/src/util/debug/DebugPrint.ts
  fission/src/util/threejs/MeshCreation.ts
  fission/vite.config.ts
Labels: engine

#969 Non-BRep Mesh Support
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Components.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Parser.py
Labels: fusion

#970 Basic Passive Constraints
  fission/public/test_mira/HingeTestFission_v1.mira
  fission/public/test_mira/SliderTestFission_v2.mira
  fission/src/Synthesis.tsx
  fission/src/mirabuf/MirabufParser.ts
  fission/src/mirabuf/MirabufSceneObject.ts
  fission/src/systems/physics/PhysicsSystem.ts
  fission/src/test/PhysicsSystem.test.ts
  fission/src/util/debug/DebugPrint.ts
Labels: engine
