Repository Autodesk/synthesis, pull requests merged in 2025-07, with the labels that each got.

#1177 Intake Multiple Gamepieces
  fission/src/mirabuf/IntakeSensorSceneObject.ts
  fission/src/mirabuf/MirabufSceneObject.ts
  fission/src/systems/preferences/PreferenceTypes.ts
  fission/src/systems/simulation/behavior/synthesis/GamepieceManipBehavior.ts
  fission/src/ui/panels/configuring/assembly-config/interfaces/ConfigureGamepiecePickupInterface.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/ConfigureShotTrajectoryInterface.tsx
Labels: ui/ux, gameplay

#1184 World.ts Unit Tests Created `[AARD-1933]`
  fission/src/test/World.test.ts
Labels: testing

#1186 Maximum quality settings `[AARD-1928]`
  fission/src/systems/PerformanceMonitor.ts
  fission/src/systems/World.ts
  fission/src/systems/preferences/PreferencesSystem.ts
Labels: rendering, ui/ux

#1152 Mitigate levitation issue
  fission/src/systems/physics/PhysicsSystem.ts
Labels: bug, physics

#1185 Exporter Reloading
  exporter/SynthesisFusionAddin/Synthesis.py
  exporter/SynthesisFusionAddin/src/UI/ConfigCommand.py
Labels: exporter

#1191 Fix Premature Performance Alert `[AARD-1928]`
  fission/src/systems/PerformanceMonitor.ts
Labels: bug, ui/ux

#1171 Input system testing `[AARD-1934]`
  fission/src/systems/input/InputSystem.ts
  fission/src/test/InputSystem.test.ts
Labels: testing

#1197 Document Swerve Drivetrain Detection `[AARD-1978]`
  docs/swerve_detection.md
Labels: documentation

#1181 Preference System Unit Tests `[AARD-1936]`
  fission/src/systems/preferences/PreferencesSystem.ts
  fission/src/test/PreferencesSystem.test.ts
Labels: testing

#1192 Simulator Field Data Dev Tool `[AARD-1914]`
  fission/src/Synthesis.tsx
  fission/src/mirabuf/FieldMiraEditor.ts
  fission/src/test/FieldMiraEditor.test.ts
  fission/src/ui/components/MainHUD.tsx
  fission/src/ui/panels/DeveloperToolPanel.tsx
Labels: ui/ux, mirabuf

#1205 fix(ci): avoid storing empty cache
  .github/workflows/FissionUnitTest.yml
Labels: hotfix

#1201 Bug: Hides touch control schemes if not supported by device `AARD-1958`
  fission/src/ui/panels/configuring/initial-config/InputSchemeSelection.tsx
Labels: bug, gameplay

#1204 Make Global Functions Non-Optional `[AARD-1986]`
  fission/src/aps/APS.ts
  fission/src/aps/APSDataManagement.ts
  fission/src/mirabuf/MirabufLoader.ts
  fission/src/mirabuf/MirabufSceneObject.ts
  fission/src/systems/PerformanceMonitor.ts
  fission/src/systems/scene/SceneRenderer.ts
  fission/src/systems/simulation/SimulationSystem.ts
  fission/src/ui/components/DragModeIndicator.tsx
  fission/src/ui/components/GlobalUIComponent.tsx
  fission/src/ui/components/GlobalUIControls.ts
  fission/src/ui/components/MainHUD.tsx
  fission/src/ui/modals/MainMenuModal.tsx
  fission/src/ui/modals/configuring/SettingsModal.tsx
  fission/src/ui/modals/mirabuf/ImportLocalMirabufModal.tsx
  fission/src/ui/panels/DebugPanel.tsx
  fission/src/ui/panels/mirabuf/ImportMirabufPanel.tsx
  fission/src/ui/panels/simulation/WiringPanel.tsx
Labels: refactor

#1133 Setuptools Version Bump `[AARD-1898]`
  installer/exporter/Windows/requirements.txt
Labels: dependencies

#1170 Exporter Materials Tagging `[AARD-1880]`
  exporter/SynthesisFusionAddin/src/Parser/ExporterOptions.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Components.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Parser.py
  exporter/SynthesisFusionAddin/src/UI/ConfigCommand.py
  exporter/SynthesisFusionAddin/src/UI/GeneralConfigTab.py
  exporter/SynthesisFusionAddin/src/UI/IconPaths.py
  exporter/SynthesisFusionAddin/src/UI/TaggingConfigTab.py
Labels: ui/ux, exporter

#1206 APS Testing `[AARD-1941]`
  fission/src/aps/APS.ts
  fission/src/test/APSTesting.test.ts
  fission/src/ui/panels/DebugPanel.tsx
Labels: testing

#1212 Save Settings Logic [`AARD-1990`]
  fission/src/ui/modals/configuring/SettingsModal.tsx
Labels: ui/ux

#1213 Clean Up Center of Mass Indicator on Dispose `[AARD-1987]`
  fission/src/mirabuf/MirabufSceneObject.ts
Labels: bug, ui/ux

#1200 Mirabuf Testing [`AARD-1940`]
  fission/src/test/mirabuf/EjectableSceneObject.test.ts
  fission/src/test/mirabuf/IntakeSensorSceneObject.test.ts
  fission/src/test/mirabuf/MirabufInstance.test.ts
  fission/src/test/mirabuf/MirabufLoader.test.ts
  fission/src/test/mirabuf/MirabufSceneObject.test.ts
  fission/src/test/mirabuf/ScoringZoneSceneObject.test.ts
  fission/src/test/mocks/jolt.ts
Labels: testing

#1172 Refactor Parser Error Handling
  .github/workflows/FusionTyping.yml
  exporter/SynthesisFusionAddin/Synthesis.py
  exporter/SynthesisFusionAddin/src/APS/APS.py
  exporter/SynthesisFusionAddin/src/ErrorHandling.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Components.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/JointHierarchy.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Joints.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Materials.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Parser.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/PhysicalProperties.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/RigidGroup.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Utilities.py
  exporter/SynthesisFusionAddin/src/Resources/PWM_icon/16x16-disabled.png
  exporter/SynthesisFusionAddin/src/Resources/PWM_icon/32x32-disabled.png
  exporter/SynthesisFusionAddin/src/Resources/PWM_icon/32x32-normal.png
  exporter/SynthesisFusionAddin/src/Types.py
  exporter/SynthesisFusionAddin/src/UI/Camera.py
  exporter/SynthesisFusionAddin/src/UI/ConfigCommand.py
  exporter/SynthesisFusionAddin/src/UI/FileDialogConfig.py
Labels: exporter, refactor

#1225 Use Local Assets for Unit Tests `[AARD-2005]`
  .github/workflows/FissionUnitTest.yml
  fission/.gitattributes
  fission/bun.lock
  fission/package.json
  fission/public/.gitignore
  fission/public/assetpack.zip
  fission/src/test/TestSetup.server.ts
  fission/vite.config.ts
Labels: packaging, testing

#1215 Fix Drag Mode Angular Momentum `[AARD-1966]`
  fission/src/systems/scene/DragModeSystem.ts
Labels: gameplay

#1217 Scene System Testing `[AARD-1938]`
  fission/src/systems/scene/CameraControls.ts
  fission/src/systems/scene/SceneRenderer.ts
  fission/src/test/scene/CameraControls.test.ts
  fission/src/test/scene/DragModeSystem.test.ts
  fission/src/test/scene/GizmoSceneObject.test.ts
  fission/src/test/scene/Joystick.test.ts
  fission/src/test/scene/SceneInteractionHandler.test.ts
  fission/src/test/scene/SceneRenderer.test.ts
Labels: testing

#1219 Refactor Input System `[AARD-1997]`
  fission/src/systems/input/DefaultInputs.ts
  fission/src/systems/input/InputSchemeManager.ts
  fission/src/systems/input/InputSystem.ts
  fission/src/systems/input/KeyboardTypes.ts
  fission/src/systems/simulation/behavior/Behavior.ts
  fission/src/systems/simulation/behavior/synthesis/ArcadeDriveBehavior.ts
  fission/src/systems/simulation/behavior/synthesis/SequenceableBehavior.ts
  fission/src/systems/simulation/behavior/synthesis/drive/SkidSteerDriveBehavior.ts
  fission/src/systems/simulation/synthesis_brain/SynthesisBrain.ts
  fission/src/test/InputSystem.test.ts
  fission/src/ui/components/Button.tsx
  fission/src/ui/components/Dropdown.tsx
  fission/src/ui/components/StyledComponents.tsx
  fission/src/ui/modals/configuring/theme-editor/NewInputSchemeModal.tsx
  fission/src/ui/panels/configuring/ChooseInputSchemePanel.tsx
  fission/src/ui/panels/configuring/assembly-config/ConfigurePanel.tsx
  fission/src/ui/panels/configuring/assembly-config/ConfigurePanelControls.ts
  fission/src/ui/panels/configuring/assembly-config/interfaces/BrainSelectionInterface.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/DrivetrainSelectionInterface.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/inputs/ConfigureInputsInterface.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/inputs/ConfigureSchemeInterface.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/inputs/EditInputInterface.tsx
  fission/src/ui/panels/configuring/initial-config/InitialConfigPanel.tsx
  fission/src/ui/panels/configuring/initial-config/InputSchemeSelection.tsx
Labels: refactor

#1216 Animation Game Piece Intake `[AARD-1973]`
  fission/src/mirabuf/EjectableSceneObject.ts
  fission/src/systems/preferences/PreferenceTypes.ts
  fission/src/test/PreferencesSystem.test.ts
  fission/src/test/mirabuf/MirabufSceneObject.test.ts
  fission/src/ui/panels/configuring/assembly-config/interfaces/ConfigureGamepiecePickupInterface.tsx
  fission/src/util/debug/DebugPrint.ts
Labels: ui/ux, gameplay

#1229 Make Gamepad and Touch Controls Mutually Exclusive `[AARD-1945]`
  fission/bun.lock
  fission/src/test/bootstrap/AppMount.test.tsx
  fission/src/ui/components/Checkbox.tsx
  fission/src/ui/components/StatefulCheckbox.tsx
  fission/src/ui/panels/RobotSwitchPanel.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/inputs/ConfigureInputsInterface.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/inputs/ConfigureSchemeInterface.tsx
Labels: ui/ux

#1236 Camera Focus Fix `[AARD-2017]`
  fission/src/systems/scene/CameraControls.ts
Labels: camera

#1235 Protected Zones Improved Config `[AARD-2012]`
  fission/src/mirabuf/ProtectedZoneSceneObject.ts
  fission/src/systems/match_mode/MatchMode.ts
  fission/src/systems/preferences/PreferenceTypes.ts
  fission/src/test/PreferencesSystem.test.ts
  fission/src/test/mirabuf/ProtectedZoneSceneObject.test.ts
  fission/src/ui/components/Dropdown.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/scoring/ManageProtectedZonesInterface.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/scoring/ProtectedZoneConfigInterface.tsx
Labels: ui/ux, gameplay

#1238 Show Alliance Color in Nametags `[AARD-2020]`
  fission/src/mirabuf/MirabufSceneObject.ts
  fission/src/ui/components/SceneOverlay.tsx
  fission/src/ui/components/SceneOverlayEvents.ts
Labels: ui/ux
