Repository Autodesk/synthesis, pull requests merged in 2025-08, with the labels that each got.

#1249 Scale Drag Mode Torque `[AARD-2035]`
  fission/src/systems/scene/DragModeSystem.ts
Labels: bug

#1245 Drag Mode Camera Focus Fix `[AARD-2028]`
  fission/src/mirabuf/MirabufSceneObject.ts
  fission/src/systems/scene/CameraControls.ts
  fission/src/systems/scene/DragModeSystem.ts
Labels: camera

#1247 Robot Falling of the Edge of the World `[AARD-2034]`
  fission/src/systems/World.ts
  fission/src/systems/simulation/RobotPositionTracker.ts
Labels: ui/ux, gameplay

#1189 Create Load Default Option for Field and Robot with Gizmo and Assembl…
  fission/src/ui/modals/MainMenuModal.tsx
  fission/src/ui/panels/mirabuf/ImportMirabufPanel.tsx
Labels: ui/ux

#1256 Utility Methods for Finding MirabufSceneObjects `[AARD-2048]`
  fission/forge.config.ts
  fission/src/main.ts
  fission/src/mirabuf/EjectableSceneObject.ts
  fission/src/systems/World.ts
  fission/src/systems/match_mode/MatchMode.ts
  fission/src/systems/match_mode/RobotDimensionTracker.ts
  fission/src/systems/scene/CameraControls.ts
  fission/src/systems/scene/DragModeSystem.ts
  fission/src/systems/scene/SceneRenderer.ts
  fission/src/systems/simulation/RobotPositionTracker.ts
  fission/src/systems/simulation/SimulationSystem.ts
  fission/src/systems/simulation/wpilib_brain/WPILibBrain.ts
  fission/src/test/RobotDimensionsTracker.test.ts
  fission/src/test/World.test.ts
  fission/src/test/mirabuf/EjectableSceneObject.test.ts
  fission/src/ui/modals/configuring/rio-config/RCConfigCANGroupModal.tsx
  fission/src/ui/modals/configuring/rio-config/RCConfigEncoderModal.tsx
  fission/src/ui/modals/configuring/rio-config/RCConfigPWMGroupModal.tsx
  fission/src/ui/modals/configuring/rio-config/RCCreateDeviceModal.tsx
  fission/src/ui/panels/DeveloperToolPanel.tsx
  fission/src/ui/panels/configuring/MatchModeConfigPanel.tsx
  fission/src/ui/panels/configuring/assembly-config/configure/AssemblySelection.tsx
  fission/src/ui/panels/simulation/AutoTestPanel.tsx
  fission/src/ui/panels/simulation/WiringPanel.tsx
Labels: refactor

#1262 Hotfix: Chrome Rendering Issue `[AARD-2058]`
  fission/src/mirabuf/MirabufInstance.ts
  fission/src/mirabuf/MirabufSceneObject.ts
Labels: hotfix

#1261 Spawning Fields without a Transform Gizmo
  fission/src/ui/modals/mirabuf/ImportLocalMirabufModal.tsx
  fission/src/ui/panels/mirabuf/ImportMirabufPanel.tsx
Labels: gameplay

#1269 Holds & Hides Cursor When Dragging View Cube `[AARD-1967]`
  fission/src/ui/components/ViewCube.tsx
Labels: ui/ux

#1271 [AARD-2078] Open Function Type Mismatch
  fission/src/ui/helpers/UIProviderHelpers.ts
Labels: ui/ux

#1263 Button Sound Fix `[AARD-2054]`
  fission/src/ui/UIProvider.tsx
  fission/src/ui/components/AnalyticsConsent.tsx
  fission/src/ui/components/ContextMenu.tsx
  fission/src/ui/components/MainHUD.tsx
  fission/src/ui/components/Modal.tsx
  fission/src/ui/components/Panel.tsx
  fission/src/ui/components/SelectButton.tsx
  fission/src/ui/components/SelectMenu.tsx
  fission/src/ui/components/StyledComponents.tsx
  fission/src/ui/components/TransformGizmoControl.tsx
  fission/src/ui/components/simulation/FlowControls.tsx
  fission/src/ui/modals/MainMenuModal.tsx
  fission/src/ui/modals/MatchResultsModal.tsx
  fission/src/ui/modals/configuring/RoboRIOModal.tsx
  fission/src/ui/modals/configuring/SettingsModal.tsx
  fission/src/ui/modals/mirabuf/ImportLocalMirabufModal.tsx
  fission/src/ui/panels/DebugPanel.tsx
  fission/src/ui/panels/DeveloperToolPanel.tsx
  fission/src/ui/panels/RobotSwitchPanel.tsx
  fission/src/ui/panels/configuring/CameraSelectionPanel.tsx
  fission/src/ui/panels/configuring/MatchModeConfigPanel.tsx
  fission/src/ui/panels/configuring/assembly-config/ConfigurePanel.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/AllianceSelectionInterface.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/BrainSelectionInterface.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/ConfigureGamepiecePickupInterface.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/ConfigureShotTrajectoryInterface.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/SequentialBehaviorsInterface.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/SimulationInterface.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/inputs/ConfigureSchemeInterface.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/inputs/EditInputInterface.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/scoring/ConfigureScoringZonesInterface.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/scoring/ScoringZoneConfigInterface.tsx
  fission/src/ui/panels/configuring/initial-config/InitialConfigPanel.tsx
  fission/src/ui/panels/configuring/initial-config/InputSchemeSelection.tsx
  fission/src/ui/panels/mirabuf/ImportMirabufPanel.tsx
  fission/src/ui/panels/simulation/AutoTestPanel.tsx
  fission/src/ui/panels/simulation/DriverStationPanel.tsx
  fission/src/ui/panels/simulation/WiringPanel.tsx
Labels: sound

#1220 Websocket Prediction Spike
  client-prediction-spike/.gitignore
  client-prediction-spike/client/client.js
  client-prediction-spike/client/dashboard.html
  client-prediction-spike/client/index.html
  client-prediction-spike/package.json
  client-prediction-spike/server.js
Labels: no-merge, gameplay, testing-spike

#1240 WebRTC Technology and Peer to Peer Architecture Spike
  p2p-spike/.gitignore
  p2p-spike/DisplayManager.ts
  p2p-spike/PeerConnection.ts
  p2p-spike/README.md
  p2p-spike/RobotClient.ts
  p2p-spike/bun.lock
  p2p-spike/client.html
  p2p-spike/dashboard.html
  p2p-spike/package.json
  p2p-spike/server.ts
  p2p-spike/tsconfig.json
  p2p-spike/types.ts
  p2p-spike/utils.ts
Labels: no-merge, testing-spike

#1243 Proper Error Handling When No Grounded Node Found
  exporter/SynthesisFusionAddin/src/ErrorHandling.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/JointHierarchy.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Parser.py
  exporter/SynthesisFusionAddin/src/UI/ConfigCommand.py
  exporter/SynthesisFusionAddin/web/src/lib/index.ts
Labels: bug

#1272 Make Configure Asset Panel Reactive `[AARD-2074]`
  fission/src/mirabuf/MirabufSceneObject.ts
  fission/src/ui/UIProvider.tsx
  fission/src/ui/components/AnalyticsConsent.tsx
  fission/src/ui/components/ContextMenu.tsx
  fission/src/ui/components/MainHUD.tsx
  fission/src/ui/components/Modal.tsx
  fission/src/ui/components/Panel.tsx
  fission/src/ui/components/SelectButton.tsx
  fission/src/ui/components/SelectMenu.tsx
  fission/src/ui/components/StyledComponents.tsx
  fission/src/ui/components/TransformGizmoControl.tsx
  fission/src/ui/components/simulation/FlowControls.tsx
  fission/src/ui/modals/MainMenuModal.tsx
  fission/src/ui/modals/MatchResultsModal.tsx
  fission/src/ui/modals/common/ConfirmModal.tsx
  fission/src/ui/modals/configuring/RoboRIOModal.tsx
  fission/src/ui/modals/configuring/SettingsModal.tsx
  fission/src/ui/modals/mirabuf/ImportLocalMirabufModal.tsx
  fission/src/ui/panels/DebugPanel.tsx
  fission/src/ui/panels/DeveloperToolPanel.tsx
  fission/src/ui/panels/RobotSwitchPanel.tsx
  fission/src/ui/panels/configuring/CameraSelectionPanel.tsx
  fission/src/ui/panels/configuring/assembly-config/ConfigurePanel.tsx
  fission/src/ui/panels/configuring/assembly-config/configure/AssemblySelection.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/AllianceSelectionInterface.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/BrainSelectionInterface.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/ConfigureGamepiecePickupInterface.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/ConfigureShotTrajectoryInterface.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/SequentialBehaviorsInterface.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/SimulationInterface.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/inputs/ConfigureSchemeInterface.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/inputs/EditInputInterface.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/scoring/ConfigureScoringZonesInterface.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/scoring/ScoringZoneConfigInterface.tsx
  fission/src/ui/panels/configuring/initial-config/InitialConfigPanel.tsx
  fission/src/ui/panels/configuring/initial-config/InputSchemeSelection.tsx
  fission/src/ui/panels/simulation/AutoTestPanel.tsx
  fission/src/ui/panels/simulation/DriverStationPanel.tsx
  fission/src/ui/panels/simulation/WiringPanel.tsx
Labels: bug

#1276 Store Protected Zones in Devtools `[AARD-2064]`
  fission/src/Window.d.ts
  fission/src/mirabuf/FieldMiraEditor.ts
  fission/src/mirabuf/MirabufSceneObject.ts
  fission/src/systems/World.ts
Labels: gameplay

#1273 Refactor Mirabuf Loading System `[AARD-2060]`
  .github/workflows/FissionUnitTest.yml
  fission/manifest.d.ts
  fission/package.json
  fission/public/assetpack.zip
  fission/src/mirabuf/DefaultAssetLoader.ts
  fission/src/mirabuf/MirabufLoader.ts
  fission/src/mirabuf/MirabufSceneObject.ts
  fission/src/test/bootstrap/AppMount.test.tsx
  fission/src/test/mirabuf/DefaultAssets.test.ts
  fission/src/test/mirabuf/FieldMiraEditor.test.ts
  fission/src/test/mirabuf/MirabufLoader.test.ts
  fission/src/test/mirabuf/MirabufParser.test.ts
  fission/src/test/mirabuf/MirabufSceneObject.test.ts
  fission/src/test/mirabuf/__snapshots__/MirabufLoader.test.ts.snap
  fission/src/test/physics/Mechanism.test.ts
  fission/src/test/physics/PhysicsSystemRobotSpawning.test.ts
  fission/src/ui/modals/MainMenuModal.tsx
  fission/src/ui/modals/mirabuf/ImportLocalMirabufModal.tsx
  fission/src/ui/panels/DebugPanel.tsx
  fission/src/ui/panels/DeveloperToolPanel.tsx
  fission/src/ui/panels/configuring/assembly-config/ConfigTypes.ts
  fission/src/ui/panels/mirabuf/ImportMirabufPanel.tsx
  fission/src/util/Utility.ts
  fission/tsconfig.json
  fission/tsconfig.node.json
  fission/update_manifest.ts
  fission/vite.config.ts
Labels: refactor

#1285 Documentation Updates `[AARD-2027]`
  CONTRIBUTING.md
  README.md
  exporter/README.md
  exporter/SynthesisFusionAddin/README.md
  fission/README.md
  fission/package.json
  fission/src/systems/World.md
  fission/src/systems/input/InputSystem.md
  fission/src/systems/physics/PhysicsSystem.md
  fission/src/systems/scene/SceneRenderer.md
  fission/src/systems/simulation/SimulationSystem.md
  installer/README.md
  protocols/README.md
  simulation/README.md
  tutorials/README.md
  tutorials/img/code-sim/can-config.png
Labels: documentation

#1293 More Analytics Events `[AARD-2097]`
  fission/src/systems/analytics/AnalyticsSystem.ts
  fission/src/systems/match_mode/MatchMode.ts
  fission/src/systems/match_mode/MatchModeAnalyticsUtils.ts
  fission/src/systems/scene/DragModeSystem.ts
  fission/src/ui/modals/MainMenuModal.tsx
  fission/src/ui/modals/configuring/SettingsModal.tsx
  fission/src/ui/panels/configuring/CreateNewMatchModeConfigPanel.tsx
  fission/src/ui/panels/configuring/MatchModeConfigPanel.tsx
Labels: analytics

#1297 Exporter: Material Parsing std Error `[AARD-2109]`
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Materials.py
Labels: bug
