Repository Autodesk/synthesis, pull requests merged in 2025-06, with the labels that each got.

#1129 Update JS Dependencies [AARD-1889]
  fission/package.json
Labels: dependencies

#1128 Main Menu Screen `[AARD-1878]`
  fission/src/Synthesis.tsx
  fission/src/ui/components/Modal.tsx
  fission/src/ui/modals/MainMenuModal.tsx
Labels: ui/ux

#1140 Intake Zone Persistent Visibility
  fission/src/mirabuf/IntakeSensorSceneObject.ts
  fission/src/mirabuf/MirabufSceneObject.ts
  fission/src/systems/preferences/PreferenceTypes.ts
  fission/src/ui/panels/configuring/assembly-config/interfaces/ConfigureGamepiecePickupInterface.tsx
Labels: ui/ux

#1137 Center camera on all axis on focus
  fission/src/mirabuf/MirabufSceneObject.ts
Labels: gameplay

#1107 The Dreaded `ConfigCommand.py` Refactor `[AARD-1764]`
  exporter/SynthesisFusionAddin/src/GlobalManager.py
  exporter/SynthesisFusionAddin/src/Parser/ExporterOptions.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/PhysicalProperties.py
  exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/RigidGroup.py
  exporter/SynthesisFusionAddin/src/Resources/HTML/info.html
  exporter/SynthesisFusionAddin/src/Types.py
  exporter/SynthesisFusionAddin/src/UI/ConfigCommand.py
  exporter/SynthesisFusionAddin/src/UI/Configuration/SerialCommand.py
  exporter/SynthesisFusionAddin/src/UI/FileDialogConfig.py
  exporter/SynthesisFusionAddin/src/UI/GamepieceConfigTab.py
  exporter/SynthesisFusionAddin/src/UI/Handlers.py
  exporter/SynthesisFusionAddin/src/UI/JointConfigTab.py
  exporter/SynthesisFusionAddin/tools/format.py
Labels: exporter, refactor

#1070 Quality Configuration
  fission/postcss.config.js
  fission/src/Synthesis.tsx
  fission/src/systems/preferences/PreferenceTypes.ts
  fission/src/systems/preferences/PreferencesSystem.ts
  fission/src/systems/scene/SceneRenderer.ts
  fission/src/ui/components/StyledComponents.tsx
  fission/src/ui/modals/configuring/SettingsModal.tsx
  fission/src/ui/panels/GraphicsSettingsPanel.tsx
  fission/tailwind.config.mjs
Labels: ui/ux, gameplay

#1151 Match Mode Infrastructure `[AARD-1892]`
  fission/src/systems/MatchMode.ts
  fission/src/systems/input/InputSystem.ts
  fission/src/systems/simulation/SimulationSystem.ts
  fission/src/ui/components/MainHUD.tsx
  fission/src/ui/modals/MatchResultsModal.tsx
  fission/src/ui/panels/information/ScoreboardPanel.tsx
Labels: gameplay

#1135 Sound Effects [AARD-1887]
  NOTICE.txt
  fission/src/assets/sound-files/ButtonPress.mp3
  fission/src/assets/sound-files/CheckboxPress.wav
  fission/src/assets/sound-files/DullClick.wav
  fission/src/systems/preferences/PreferenceTypes.ts
  fission/src/systems/sound/SoundPlayer.ts
  fission/src/ui/components/Button.tsx
  fission/src/ui/components/Checkbox.tsx
  fission/src/ui/components/Dropdown.tsx
  fission/src/ui/components/MainHUD.tsx
  fission/src/ui/components/Modal.tsx
  fission/src/ui/components/Panel.tsx
  fission/src/ui/components/TransformGizmoControl.tsx
  fission/src/ui/modals/configuring/SettingsModal.tsx
  fission/src/ui/modals/mirabuf/ImportLocalMirabufModal.tsx
  fission/src/ui/panels/configuring/CameraSelectionPanel.tsx
  fission/src/ui/panels/configuring/assembly-config/ConfigurePanel.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/BrainSelectionInterface.tsx
  fission/src/ui/panels/mirabuf/ImportMirabufPanel.tsx
  fission/src/ui/panels/simulation/AutoTestPanel.tsx
  fission/src/util/Utility.ts
Labels: ui/ux

#1148 Hot Refresh Support
  fission/src/Synthesis.tsx
  fission/src/main.tsx
  fission/src/systems/scene/SceneRenderer.ts
  fission/src/ui/ModalContext.tsx
  fission/src/ui/PanelContext.tsx
  fission/src/ui/ThemeContext.tsx
  fission/src/ui/components/AnalyticsConsent.tsx
  fission/src/ui/components/BespokeGraph.tsx
  fission/src/ui/components/ContextMenu.tsx
  fission/src/ui/components/Dropdown.tsx
  fission/src/ui/components/GlobalUIComponent.tsx
  fission/src/ui/components/MainHUD.tsx
  fission/src/ui/components/Modal.tsx
  fission/src/ui/components/Panel.tsx
  fission/src/ui/components/Skybox.tsx
  fission/src/ui/components/StyledComponents.tsx
  fission/src/ui/components/ToggleButtonGroup.tsx
  fission/src/ui/helpers/UseModalManager.tsx
  fission/src/ui/helpers/UsePanelManager.tsx
  fission/src/ui/helpers/UseThemeHelpers.tsx
  fission/src/ui/modals/MainMenuModal.tsx
  fission/src/ui/modals/MatchResultsModal.tsx
  fission/src/ui/modals/configuring/RoboRIOModal.tsx
  fission/src/ui/modals/configuring/SettingsModal.tsx
  fission/src/ui/modals/configuring/rio-config/RCConfigCANGroupModal.tsx
  fission/src/ui/modals/configuring/rio-config/RCConfigEncoderModal.tsx
  fission/src/ui/modals/configuring/rio-config/RCConfigPWMGroupModal.tsx
  fission/src/ui/modals/configuring/rio-config/RCCreateDeviceModal.tsx
  fission/src/ui/modals/configuring/theme-editor/AssignNewSchemeModal.tsx
  fission/src/ui/modals/configuring/theme-editor/DeleteAllThemesModal.tsx
  fission/src/ui/modals/configuring/theme-editor/DeleteThemeModal.tsx
  fission/src/ui/modals/configuring/theme-editor/NewInputSchemeModal.tsx
  fission/src/ui/modals/configuring/theme-editor/NewThemeModal.tsx
  fission/src/ui/modals/configuring/theme-editor/ThemeEditorModal.tsx
  fission/src/ui/modals/mirabuf/ImportLocalMirabufModal.tsx
  fission/src/ui/panels/DebugPanel.tsx
  fission/src/ui/panels/RobotSwitchPanel.tsx
  fission/src/ui/panels/configuring/ChooseInputSchemePanel.tsx
  fission/src/ui/panels/configuring/assembly-config/ConfigurePanel.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/ConfigureGamepiecePickupInterface.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/ConfigureShotTrajectoryInterface.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/SimulationInterface.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/inputs/ConfigureInputsInterface.tsx
  fission/src/ui/panels/configuring/initial-config/InitialConfigPanel.tsx
  fission/src/ui/panels/information/ScoreboardPanel.tsx
  fission/src/ui/panels/mirabuf/ImportMirabufPanel.tsx
  fission/src/ui/panels/simulation/AutoTestPanel.tsx
  fission/src/ui/panels/simulation/WiringPanel.tsx
Labels: ui/ux

#1104 Input System Touch Controls
  fission/src/Synthesis.tsx
  fission/src/systems/input/DefaultInputs.ts
  fission/src/systems/input/InputSchemeManager.ts
  fission/src/systems/input/InputSystem.ts
  fission/src/systems/preferences/PreferenceTypes.ts
  fission/src/systems/scene/Joystick.ts
  fission/src/systems/scene/SceneRenderer.ts
  fission/src/ui/components/Checkbox.tsx
  fission/src/ui/components/MainHUD.tsx
  fission/src/ui/components/TouchControls.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/inputs/ConfigureSchemeInterface.tsx
  fission/src/ui/panels/configuring/assembly-config/interfaces/inputs/EditInputInterface.tsx
  fission/src/ui/panels/configuring/initial-config/InputSchemeSelection.tsx
  fission/vite.config.ts
Labels: gameplay

#1134 Add View Cube to the screen
  fission/src/Synthesis.tsx
  fission/src/systems/preferences/PreferenceTypes.ts
  fission/src/systems/scene/CameraControls.ts
  fission/src/systems/scene/ScreenInteractionHandler.ts
  fission/src/ui/components/SceneOverlay.tsx
  fission/src/ui/components/ViewCube.tsx
  fission/src/ui/helpers/UseModalManager.tsx
  fission/src/ui/modals/configuring/SettingsModal.tsx
Labels: camera

#1145 Created Drag Mode (previously god mode)
  fission/src/Synthesis.tsx
  fission/src/systems/World.ts
  fission/src/systems/physics/PhysicsSystem.ts
  fission/src/systems/scene/CameraControls.ts
  fission/src/systems/scene/DragModeSystem.ts
  fission/src/systems/scene/SceneRenderer.ts
  fission/src/test/PhysicsSystem.test.ts
  fission/src/ui/components/DragModeIndicator.tsx
  fission/src/ui/panels/DebugPanel.tsx
Labels: gameplay

#1162 Remove init scripts
  init.bat
  init.sh
Labels: documentation

#1166 Sensitivity Sliders
  fission/src/systems/preferences/PreferenceTypes.ts
  fission/src/systems/scene/CameraControls.ts
  fission/src/ui/components/ViewCube.tsx
  fission/src/ui/modals/configuring/SettingsModal.tsx
Labels: gameplay

#1159 Configure Assets Save Cancel
  fission/src/mirabuf/MirabufSceneObject.ts
  fission/src/systems/preferences/PreferenceTypes.ts
  fission/src/systems/preferences/PreferencesSystem.ts
  fission/src/ui/panels/configuring/assembly-config/ConfigurePanel.tsx
Labels: ui/ux

#1164 [Snyk] Upgrade three from 0.159.0 to 0.177.0
  fission/package.json
Labels: dependencies

#1161 vite.config.ts Updated `[AARD-1953]`
  fission/vite.config.ts
Labels: testing

#1163 Bulk Actions Assets
  fission/src/ui/panels/mirabuf/ImportMirabufPanel.tsx
Labels: ui/ux

#1167 Clamp Function Unit Test `[AARD-1932]`
  fission/src/test/PhysicsSystem.test.ts
  fission/src/test/util/Clamp.test.ts
Labels: testing
